import type { ConfigPreset, ConfigState } from '@/types/configurator';
import { defaultPartStates } from './interactive-parts';

export const defaultConfig: ConfigState = {
  activePart: 'body',
  bodyColor: '#1a1a1a',
  bodyMaterial: 'glossy',
  wheelColor: '#1a1a1a',
  wheelMaterial: 'metallic',
  lightColor: '#ff6600',
  lightIntensity: 5.0,
  accentColor: '#ff6600',
  windowTint: '#333333',
  windowOpacity: 0.3,
  cameraPreset: 'Overview',
  autoRotate: true,
  wingsOpen: false,
  isMobile: false,
  partStates: { ...defaultPartStates },
  explodeAmount: 0,
};

export const configPresets: ConfigPreset[] = [
  {
    name: 'Stock',
    bodyColor: '#1a1a1a',
    bodyMaterial: 'glossy',
    wheelColor: '#1a1a1a',
    wheelMaterial: 'metallic',
    lightColor: '#ff6600',
    lightIntensity: 5.0,
    accentColor: '#ff6600',
    windowTint: '#333333',
    windowOpacity: 0.3,
  },
  {
    name: 'Midnight Purple',
    bodyColor: '#3d1a6b',
    bodyMaterial: 'metallic',
    wheelColor: '#1a1a1a',
    wheelMaterial: 'glossy',
    lightColor: '#8b1aff',
    lightIntensity: 6.0,
    accentColor: '#8b1aff',
    windowTint: '#333333',
    windowOpacity: 0.2,
  },
  {
    name: 'Arctic White',
    bodyColor: '#e8e8e8',
    bodyMaterial: 'satin',
    wheelColor: '#b0b0b0',
    wheelMaterial: 'metallic',
    lightColor: '#1a8bff',
    lightIntensity: 5.0,
    accentColor: '#1a8bff',
    windowTint: '#888888',
    windowOpacity: 0.4,
  },
  {
    name: 'Rosso Corsa',
    bodyColor: '#8b1a1a',
    bodyMaterial: 'glossy',
    wheelColor: '#1a1a1a',
    wheelMaterial: 'glossy',
    lightColor: '#ff1a1a',
    lightIntensity: 5.5,
    accentColor: '#ff1a1a',
    windowTint: '#333333',
    windowOpacity: 0.25,
  },
  {
    name: 'Carbon Stealth',
    bodyColor: '#2a2a2a',
    bodyMaterial: 'carbon',
    wheelColor: '#4a4a4a',
    wheelMaterial: 'satin',
    lightColor: '#00ffee',
    lightIntensity: 4.5,
    accentColor: '#00ffee',
    windowTint: '#333333',
    windowOpacity: 0.15,
  },
];
