import type { InteractivePart, PartTransformDef, InteractiveGroup } from '@/types/configurator';

/**
 * Maps each interactive part to its node name and transform parameters.
 *
 * Model orientation: Y = up, +Z = front, +X = right side.
 * Node names come from the GLTF scene graph (parent group nodes).
 */
export const interactivePartDefs: Record<InteractivePart, PartTransformDef> = {
  doorL: {
    nodeName: 'detach_door_L_60',
    type: 'translate',
    direction: [-1, 0.3, 0],
    maxDistance: 3.0,
    explodeDirection: [-1, 0.3, 0],
    explodeDistance: 4.5,
    label: 'Left Door',
  },
  doorR: {
    nodeName: 'detach_door_R_60',
    type: 'translate',
    direction: [1, 0.3, 0],
    maxDistance: 3.0,
    explodeDirection: [1, 0.3, 0],
    explodeDistance: 4.5,
    label: 'Right Door',
  },
  trunk: {
    nodeName: 'detach_trunk_50',
    type: 'translate',
    direction: [0, 0.5, -0.5],
    maxDistance: 2.5,
    explodeDirection: [0, 0.8, -0.5],
    explodeDistance: 4.0,
    label: 'Trunk',
  },
  skirtL: {
    nodeName: 'detach_skirt_L_15',
    type: 'translate',
    direction: [-1, -0.2, 0],
    maxDistance: 2.0,
    explodeDirection: [-1, -0.2, 0],
    explodeDistance: 3.5,
    label: 'Left Skirt',
  },
  skirtR: {
    nodeName: 'detach_skirt_R_15',
    type: 'translate',
    direction: [1, -0.2, 0],
    maxDistance: 2.0,
    explodeDirection: [1, -0.2, 0],
    explodeDistance: 3.5,
    label: 'Right Skirt',
  },
  lip: {
    nodeName: 'detach_lip_5',
    type: 'translate',
    direction: [0, -0.1, 1],
    maxDistance: 2.0,
    explodeDirection: [0, -0.2, 1],
    explodeDistance: 3.0,
    label: 'Front Lip',
  },
  diffuser: {
    nodeName: 'detach_diffuser_5',
    type: 'translate',
    direction: [0, -0.1, -1],
    maxDistance: 2.0,
    explodeDirection: [0, -0.2, -1],
    explodeDistance: 3.0,
    label: 'Rear Diffuser',
  },
  wing: {
    nodeName: 'detach_wing_10',
    type: 'translate',
    direction: [0, 1, 0],
    maxDistance: 2.0,
    explodeDirection: [0, 1, -0.3],
    explodeDistance: 4.0,
    label: 'Wing',
  },
  glass: {
    nodeName: 'glass_detachable',
    type: 'translate',
    direction: [0, 1, 0],
    maxDistance: 2.0,
    explodeDirection: [0, 1, 0.2],
    explodeDistance: 4.0,
    label: 'Glass',
  },
  wheelFR: {
    nodeName: 'anteriore_dest',
    type: 'translate',
    direction: [1, 0, 0.5],
    maxDistance: 2.5,
    explodeDirection: [1, 0, 0.5],
    explodeDistance: 4.0,
    label: 'Front Right Wheel',
  },
  wheelFL: {
    nodeName: 'anteriore_sins',
    type: 'translate',
    direction: [-1, 0, 0.5],
    maxDistance: 2.5,
    explodeDirection: [-1, 0, 0.5],
    explodeDistance: 4.0,
    label: 'Front Left Wheel',
  },
  wheelRR: {
    nodeName: 'post_dest',
    type: 'translate',
    direction: [1, 0, -0.5],
    maxDistance: 2.5,
    explodeDirection: [1, 0, -0.5],
    explodeDistance: 4.0,
    label: 'Rear Right Wheel',
  },
  wheelRL: {
    nodeName: 'ppst_sinis',
    type: 'translate',
    direction: [-1, 0, -0.5],
    maxDistance: 2.5,
    explodeDirection: [-1, 0, -0.5],
    explodeDistance: 4.0,
    label: 'Rear Left Wheel',
  },
  chassis: {
    nodeName: 'chassis',
    type: 'translate',
    direction: [0, -0.5, 0],
    maxDistance: 1.5,
    explodeDirection: [0, -1, 0],
    explodeDistance: 3.0,
    label: 'Chassis',
  },
  piston: {
    nodeName: 'front_piston',
    type: 'translate',
    direction: [0, 0.5, 1],
    maxDistance: 1.5,
    explodeDirection: [0, 0.5, 1],
    explodeDistance: 3.0,
    label: 'Front Piston',
  },
  exhaust: {
    nodeName: 'emissive_mesh',
    type: 'translate',
    direction: [0, -0.3, -1],
    maxDistance: 1.5,
    explodeDirection: [0, -0.3, -1],
    explodeDistance: 3.0,
    label: 'Exhaust',
  },
  windshield: {
    nodeName: 'glass_9',
    type: 'translate',
    direction: [0, 1, 0.3],
    maxDistance: 2.0,
    explodeDirection: [0, 1, 0.3],
    explodeDistance: 4.0,
    label: 'Windshield',
  },
};

/** UI groups - paired parts toggle together */
export const interactiveGroups: InteractiveGroup[] = [
  { label: 'Doors', parts: ['doorL', 'doorR'] },
  { label: 'Trunk', parts: ['trunk'] },
  { label: 'Side Skirts', parts: ['skirtL', 'skirtR'] },
  { label: 'Bumper', parts: ['lip', 'diffuser'] },
  { label: 'Wing', parts: ['wing'] },
  { label: 'Glass', parts: ['glass'] },
  { label: 'Wheels', parts: ['wheelFL', 'wheelFR', 'wheelRL', 'wheelRR'] },
  { label: 'Chassis', parts: ['chassis'] },
  { label: 'Aero', parts: ['piston'] },
  { label: 'Exhaust', parts: ['exhaust'] },
  { label: 'Windshield', parts: ['windshield'] },
];

export const defaultPartStates: Record<InteractivePart, boolean> = {
  doorL: false,
  doorR: false,
  trunk: false,
  skirtL: false,
  skirtR: false,
  lip: false,
  diffuser: false,
  wing: false,
  glass: false,
  wheelFL: false,
  wheelFR: false,
  wheelRL: false,
  wheelRR: false,
  chassis: false,
  piston: false,
  exhaust: false,
  windshield: false,
};

export const allInteractiveParts = Object.keys(interactivePartDefs) as InteractivePart[];
